import { RuleCategory } from '../../domain/RuleCategory.js';
import { type Rule, defineRule } from '../Rule.js';
import { distinctHits, evidence, firstMatch, plural } from '../support.js';

const CITATION_TOKENS = [
  'oaicite',
  'contentreference',
  'utm_source=chatgpt.com',
  'turn0search',
  'citeturn',
] as const;

const ASSISTANT_PHRASES = [
  'as an ai language model',
  "certainly! here's",
  'certainly! here is',
  "sure! here's",
  "here's a modern, responsive",
  'i hope this helps',
  "let me know if you'd like me to",
  'feel free to customize this',
  'as requested, here is',
  "i've created a landing",
  'you can replace this with your',
] as const;

const DEFAULT_TITLES = ['react app', 'vite app', 'vite + react', 'nuxt app', 'svelte app'] as const;

const PLACEHOLDER_BRANDS = [
  'your brand name',
  'your business name',
  'company name here',
  'brand name here',
  'your logo here',
  'your name here',
  'startup name',
  'product name here',
  'your company name',
] as const;

/**
 * "Your Company" as a brand slot rather than as English, so case-SENSITIVELY: a
 * template leaves it title-cased, prose writes "Start your company". At weight 16
 * the loose version fired on 0% of generated pages and 7.7% of hand-built ones.
 */
const COMPANY_SLOT = /\bYour Company\b(?!['’]s)/;
const COMPANY_SLOT_ANY_CASE =
  /(?:©|\(c\)|copyright)\s*(?:\d{4}\s*)?(?:[-–]\s*\d{4}\s*)?your company\b|your company,?\s+(?:inc|llc|ltd|corp|co)\b/i;

export const unfinishedRules: readonly Rule[] = [
  defineRule({
    id: 'unfinished.citation-tokens',
    category: RuleCategory.Unfinished,
    weight: 35,
    label: 'Chatbot citation codes left in the text',
    phrase: 'chatbot citation markers left in the text',
    evaluate: (ctx) => {
      const hits = distinctHits(ctx.content.lower, CITATION_TOKENS);
      return hits.length > 0 ? hits.join(', ') : null;
    },
  }),

  defineRule({
    id: 'unfinished.assistant-reply',
    category: RuleCategory.Unfinished,
    weight: 30,
    label: 'A chatbot reply left in the copy',
    phrase: "a chatbot's reply sitting in the copy",
    evaluate: (ctx) => {
      const hits = distinctHits(ctx.content.lower, ASSISTANT_PHRASES);
      return hits.length > 0 ? `"${hits[0]}"` : null;
    },
  }),

  defineRule({
    id: 'unfinished.scaffold-title',
    category: RuleCategory.Unfinished,
    weight: 24,
    label: 'The scaffold own title, never changed',
    phrase: "the scaffold's title never changed",
    evaluate: (ctx) => {
      const title = ctx.document.title.toLowerCase();
      if (title.includes('create next app')) return 'default CNA title';
      if (
        (ctx.document.meta.description ?? '').toLowerCase().includes('generated by create next app')
      ) {
        return 'default CNA description';
      }
      return evidence(
        (DEFAULT_TITLES as readonly string[]).includes(title),
        `default "${ctx.document.title}" title`,
      );
    },
  }),

  defineRule({
    id: 'unfinished.lorem',
    category: RuleCategory.Unfinished,
    weight: 22,
    label: 'Lorem ipsum',
    phrase: 'lorem ipsum still in the copy',
    evaluate: (ctx) =>
      evidence(
        /lorem ipsum|dolor sit amet/i.test(ctx.content.text),
        'placeholder Latin still in the copy',
      ),
  }),

  defineRule({
    id: 'unfinished.brand-slot',
    category: RuleCategory.Unfinished,
    weight: 16,
    label: 'A placeholder company name',
    phrase: 'Your Company still sitting in the copy',
    evaluate: (ctx) => {
      const hits = distinctHits(ctx.content.lower, PLACEHOLDER_BRANDS);
      if (hits.length > 0) return hits[0] ?? null;
      if (COMPANY_SLOT.test(ctx.content.text) || COMPANY_SLOT_ANY_CASE.test(ctx.content.text)) {
        return 'Your Company in a brand slot';
      }
      // "Acme" is the canonical stand-in brand. Word-bounded so it misses "acmeism".
      return firstMatch(ctx.content.text, /\bAcme\b(?:\s+(?:Inc|Corp|Co|Labs|LLC|Ltd))?/i);
    },
  }),

  defineRule({
    id: 'unfinished.template-slots',
    category: RuleCategory.Unfinished,
    weight: 16,
    label: 'An unfilled template slot',
    phrase: 'an unfilled slot from the template',
    evaluate: (ctx) => {
      const { text } = ctx.content;
      if (/\b(?:tagline|headline|subheadline|description)\s+goes\s+here\b/i.test(text)) {
        return 'tagline goes here';
      }
      const bracket = firstMatch(
        text,
        /\[(?:your|insert|add|product|company|brand|target audience|benefit)[^\]]{2,40}\]/i,
      );
      if (bracket !== null) return bracket;
      return evidence(/\{\{\s*[a-z_][a-z0-9_.]{2,30}\s*\}\}/i.test(text), 'unrendered {{token}}');
    },
  }),

  defineRule({
    id: 'unfinished.raw-markdown',
    category: RuleCategory.Unfinished,
    weight: 12,
    label: 'Raw markdown showing as text',
    phrase: 'raw markdown showing as text',
    evaluate: (ctx) => {
      const { text } = ctx.content;
      let count = 0;
      if (/(?:^|\s)#{2,4}\s+[A-Z]/.test(text)) count++;
      if (/\*\*[^*\n]{2,60}\*\*/.test(text)) count++;
      if (/\[[^\]\n]{2,50}\]\(https?:\/\/[^)\s]+\)/.test(text)) count++;
      return evidence(count >= 2, plural(count, 'piece of raw markdown', 'pieces of raw markdown'));
    },
  }),

  defineRule({
    id: 'unfinished.dead-links',
    category: RuleCategory.Unfinished,
    weight: 10,
    label: 'Links that go nowhere',
    phrase: 'links that go nowhere',
    evaluate: (ctx) => {
      const dead = ctx.document.anchors.filter((anchor) => {
        const href = anchor.href.trim();
        return (
          href === '#' || href === '' || /^https?:\/\/(?:www\.)?example\.(?:com|org)/i.test(href)
        );
      }).length;
      return evidence(dead >= 5, plural(dead, 'link that goes nowhere', 'links that go nowhere'));
    },
  }),

  defineRule({
    id: 'unfinished.placeholder-art',
    category: RuleCategory.Unfinished,
    weight: 8,
    label: 'Placeholder images',
    phrase: "the theme's placeholder images",
    evaluate: (ctx) =>
      evidence(
        /placehold\.co|via\.placeholder|placekitten|placeimg|dummyimage\.com/i.test(
          ctx.document.assetRefs,
        ),
        'grey stand-in images were never replaced',
      ),
  }),
];
